---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: costaki-test-redis-pvc
  labels:
    username: costaki
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
