---
apiVersion: v1
kind: Service
metadata:
  name: costaki-test-redis-service
  labels:
    name: costaki
    env: test
spec:
  type: ClusterIP
  selector:
    username: costaki
    env: test
    app: costaki-test-redis
  ports:
  - name: costaki-test-redis-port
    port: 6379
    targetPort: 6379
