---
apiVersion: v1
kind: Service
metadata:
  name: costaki-test-flask-service
  labels:
    name: costaki
    env: test
spec:
  type: ClusterIP
  selector:
    username: costaki
    env: test
    app: costaki-test-flask
  ports:
  - name: costaki-test-flask-port
    port: 5000
    targetPort: 5000
